blank_issues_enabled: false
contact_links:
  - name: "📚 Read Jina Docs"
    url: https://docs.jina.ai/
    about: Find your solution from our documenations
  - name: Contact the Team
    url: hello@jina.ai
    about: Contact us if your question is non-technical