apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-data-head
  namespace: search-flow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-data-head


  template:
    metadata:
      labels:
        app: image-data-head
    spec:
      volumes:
        - name: shared
          emptyDir: {}
      initContainers:
      - name: init
        image: gcr.io/jina-showcase/postgres-dumper
        imagePullPolicy: Always
        command: ["python", "dump.py", "{\"table_name\": \"image_data\", \"postgres_svc\": \"postgres.postgres.svc.cluster.local\", \"shards\": 3, \"dump_path\": \"/shared\"}"]
        volumeMounts:
          - name: shared
            mountPath: /shared
      containers:
      - name: executor
        image: gcr.io/jina-showcase/custom-jina:latest
        command: ["jina"]
        args: ["pea", "--uses", "BaseExecutor", "--runtime-cls", "GRPCDataRuntime"--uses-metas", "{\"pea_id\": \"_head\"}", "--uses-with", "{\"dump_path\": \"/shared\"}", "--name", "image_data", "--identity", "9f788dbe-d553-450f-ab25-0965464fc453", "--workspace-id", "3d5527b5-34f2-403c-8d75-b1a45037e12c", "--send-routing-table", "--port-ctrl", "50192", "--timeout-ctrl", "5000", "--uses-with", "{dump_path: /shared}", "--port-in", "50193", "--port-out", "50194", "--host-in", "0.0.0.0", "--host-out", "0.0.0.0", "--socket-out", "PUSH_BIND", "--memory-hwm", "-1", "--num-part", "1", "--host", "0.0.0.0", "--port-expose", "8080", "--runtime-backend", "PROCESS", "--runtime-cls", "ZEDRuntime", "--timeout-ready", "600000", "--noblock-on-start", "--uses-after", "gcr.io/jina-showcase/match-merger", "--parallel", "3", "--replicas", "2", "--polling", "ALL", "--k8s-uses-init", "gcr.io/jina-showcase/postgres-dumper", "--k8s-uses-with-init", "{table_name: image_data, postgres_svc: postgres.postgres.svc.cluster.local, shards: 3, dump_path: /shared}"]
        ports:
          - containerPort: 50193
          - containerPort: 50194
          - containerPort: 50192
          - containerPort: 8080
        env:
        - name: JINA_LOG_LEVEL
          value: debug
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: WORKER_CLASS
          value: "uvicorn.workers.UvicornH11Worker"
        volumeMounts:
          - name: shared
            mountPath: /shared

