apiVersion: v1
kind: Service
metadata:
  name: {name}
  namespace: {namespace}
  labels:
    app: {target}
spec:
  type: {type}
  ports:
    - port: {port_in}
      targetPort: {port_in}
      name: port-in
      protocol: TCP
    - port: {port_out}
      targetPort: {port_out}
      name: port-out
      protocol: TCP
  selector:
    app: {target}