name: Docs Build

on:
  push:
    branches:
      - master

jobs:
  make-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: |
          pip install .
          ./make-doc.sh commit "${{github.event_name}} ${{github.sha}}"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.JINA_AI }}
          repository: jina-ai/jina-docs
          force: true
          directory: docs/_build/html
