name: Release CD

on:
  push:
    tags:
      - "v*"  # push to version tags trigger the build


jobs:
  update-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v2
        with:
          MAX_HEADER_LEVEL: 2
          FOLDING: false
          GITHUB_TOKEN: ${{ secrets.JINA_DEV_BOT }}
          TOC_TITLE: ''
          TARGET_PATHS: '*.md'
      #      - uses: peter-evans/dockerhub-description@v2.1.0
      #        env:
      #          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_DEVBOT_USER }}
      #          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_DEVBOT_PWD }}
      #          DOCKERHUB_REPOSITORY: jinaai/jina
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install the release version
        run: |
          pip install .
          echo ::set-env name=JINA_VERSION::${TAG_VER#"v"}
          JINA_VERSION=${{env.JINA_VERSION}} ./make-doc.sh release "release ${{github.ref}} of ${{github.repository}}"
        env:
          TAG_VER: ${{ github.ref }}
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.JINA_DEV_BOT }}
          repository: jina-ai/jina-docs
          force: true
          directory: docs/_build/html
          tags: true

  update-docker:
    needs: update-doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Set envs and versions
        run: |
          echo ${{ steps.buildx.outputs.platforms }}
          echo ::set-env name=VCS_REF::$(git rev-parse --short HEAD)
          echo ::set-env name=BUILD_DATE::$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo ::set-env name=JINA_VERSION::${TAG_VER#"v"}
        env:
          TAG_VER: ${{ github.ref }}
      - name: Run Buildx and Upload to Docker Cloud
        run: |
          docker login -u ${{ secrets.DOCKERHUB_DEVBOT_USER }} -p ${{ secrets.DOCKERHUB_DEVBOT_TOKEN }}
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6 \
            --output "type=registry" \
            --build-arg VCS_REF --build-arg BUILD_DATE --build-arg JINA_VERSION \
            -t jinaai/jina:$JINA_VERSION -t jinaai/jina:latest \
            --file ./Dockerfiles/debianx.Dockerfile .
      - name: Upload to Github Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: jina-ai/jina/jina
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          dockerfile: Dockerfiles/debianx.Dockerfile
          buildargs: BUILD_DATE, VCS_REF, JINA_VERSION
          tags: "latest, ${{env.JINA_VERSION}}"
